---
name: Build
on:
  workflow_dispatch:

jobs:
  get_environment:
    runs-on: ubuntu-latest
    outputs:
      releaseEnv: ${{ steps.getReleaseEnv.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: getReleaseEnv
        with:
          result-encoding: string
          script: |
            const RELEASE_ENVS = {
              "main": "daily",
              "^TB_BETA_.*$": "beta",
              "^TB_RELEASE_.*$": "release"
            }
            const ReleaseEnvs = new Proxy(RELEASE_ENVS, {
                get(target, prop, receiver) {
                    if (target.hasOwnProperty(prop)) {
                        return target[prop]
                    }
                    const search = Object.keys(RE).filter((key) => new RegExp(key).test(prop))
                    if (search.length === 1) {
                        return target[search[0]]
                    }
                    return undefined
                }
            })
            const branch = context.ref.replace(/^refs\/heads\//, "")
            return ReleaseEnvs[branch]
            

  dump_config:
    runs-on: ubuntu-latest
    needs: get_environment
    steps:
      - name: Dump Vars context
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RELEASE_ENV: ${{ needs.get_environment.outputs.releaseEnv }}
        run: |
          echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest
    needs: dump_config
    strategy:
      matrix:
        flavor: ["github", "playstore"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: .

      - name: Build
        shell: bash
        env:
          FLAVOR: ${{ matrix.flavor }}
        run: |
          rm -rf upload
          mkdir upload
          dd if=/dev/urandom bs=512 count=1 of=/dev/stdout | base64 > upload/${FLAVOR}_release_file.txt
          echo "1.0.2" > upload/version.txt
          echo ${GITHUB_SHA} > upload/sha.txt

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact-${{ matrix.flavor }}
          path: upload/
          if-no-files-found: error

  pre_publish:
    environment: gh_publisher
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Approval
        shell: bash
        run: |
          true

  publish:
    uses: ./.github/workflows/publish.yml
    with:
      workflow_run_id: ${{ github.run_id }}
      workflow_run_number: ${{ github.run_number }}
          
  
