---
name: Build
on:
  workflow_dispatch:

jobs:
  dump_config:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Vars context
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["github", "playstore"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: .

      - name: Build
        shell: bash
        env:
          FLAVOR: ${{ matrix.flavor }}
        run: |
          rm -rf upload
          mkdir upload
          dd if=/dev/urandom bs=512 count=1 of=/dev/stdout | base64 > upload/${FLAVOR}_release_file.txt
          echo "1.0.2" > upload/version.txt
          echo ${GITHUB_SHA} > upload/sha.txt

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact-${{ matrix.flavor }}
          path: upload/
          if-no-files-found: error

  pre_publish:
    environment: gh_publisher
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Approval
        shell: bash
        run: |
          true

  publish:
    uses: ./.github/workflows/publish.yml
    with:
      workflow_run_id: ${{ github.run_id }}
      workflow_run_number: ${{ github.run_number }}
          
  
