---
name: GH Publish
on:
  workflow_dispatch:

jobs:
  dump_config:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Vars context
        id: variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  gh_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: ${{ github.ref_name }}
          event: workflow_dispatch
          name: test-artifact-github
          path: artifacts
          check_artifacts: false
          if_no_artifact_found: fail
          allow_forks: false
